<a href="https://colab.research.google.com/github/levchenkopavlo/AI/blob/master/2_%D0%9F%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Імпортуйте модуль numpy

In [1]:
import numpy as np

# Завдання 1
Створіть масив з елементами від 1 до 12. Виведіть розмір та тип масиву

In [26]:
array = np.arange(1,13)
print(array)
print(array.size)
print(array.shape)
print(type(array))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
12
(12,)
<class 'numpy.ndarray'>


# Завдання 2
Зробіть на основі попереднього масиву матрицю з 4 стовчиками. Змініть тип даних матриці на float32. Виведіть транспоновану матрицю.

In [6]:
new_array = array.reshape(-1, 4)
new_array = new_array.astype(np.float32)

#Завдання 3
Створіть матрицю 8х8 з 0 та 1 розміщеними в шаховому порядку

In [25]:
array = np.zeros((8,8))
print(array)
array[::2,::2]=1
array[1::2,1::2]=1
print(array)


[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


# Завдання 4
Створіть випадкову матрицю 4х3. Знайдіть суму елементів в стовпчиках\рядках\усій матриці

In [60]:
array1 = np.random.rand(4,3)
print(array1)
print(array1.sum(axis=0))
print(array1.sum(axis=1))
print(array1.sum())

[[0.15220459 0.90344273 0.3255582 ]
 [0.81148459 0.78943956 0.79511976]
 [0.88307076 0.60965058 0.41227765]
 [0.73638518 0.42798865 0.1301972 ]]
[2.58314512 2.73052153 1.66315281]
[1.38120552 2.39604392 1.90499899 1.29457103]
6.976819460391549


In [62]:
# array = np.random.rand(4,3)

print(array1[array1 > 0.5])
array1[array1 > 0.5] = 1
print(array1)

[1. 1. 1. 1. 1. 1. 1.]
[[0.15220459 1.         0.3255582 ]
 [1.         1.         1.        ]
 [1.         1.         0.41227765]
 [1.         0.42798865 0.1301972 ]]


# Завдання 5
У попередній матриці від кожного рядка відніміть максимальний елемент цього рядка

In [14]:
max = array.max(axis=1, keepdims=True)
print(max)
print(array - max)

[[0.60452794]
 [0.96463357]
 [0.58778173]
 [0.60790399]]
[[-0.45049093 -0.33615511  0.        ]
 [-0.56785512 -0.21466498  0.        ]
 [ 0.         -0.26895746 -0.55448399]
 [-0.4115914  -0.45594974  0.        ]]


# Завдання 6
Є дані про вагу контейнерів для перевезення на кораблі: дрібний - 5 т,  малий - 10 т, середній - 25 т, великий - 40 т. На кораблі розміщено 20 дрібних, 5 малих, 10 середніх та 4 великих контейнерів. Знайти масу вантажу.

# Завдання 7
Тепер у нас декілька кораблів. Напишіть код для обчислення вантажу на кожному кораблі.