<a href="https://colab.research.google.com/github/levchenkopavlo/AI/blob/master/%D0%94%D0%97_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Імпортуйте модуль numpy

In [102]:
import numpy as np

#Завдання 1

Створіть масив з парними числами між 30 і 70

In [103]:
array = np.arange(30,71,2)
print(array)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


#Завдання 2
Створіть масив з 10 числами між 0(включно) та 1(не включно) див документацію

In [104]:
array = np.linspace(0., 1., num=10, endpoint=False)
print(array)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


#Завдання 4
Напишіть функцію яка приймає матрицю розміру nxn та повертає матрицю розміру (n+2) x (n+2), на краях якої розміщенні 0.

In [105]:
def array_transform(array):
  size = array.shape
  blank = np.zeros((size[0]+2, size[1]+2), int)
  print(blank)
  blank[1:-1, 1:-1] = array
  return blank

n, m = 3, 4
array = np.random.randint(1, 9, size=(n, m))
print(array)
print(array_transform(array))
# print(array.dtype)

[[3 4 3 3]
 [6 6 4 8]
 [8 2 5 2]]
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
[[0 0 0 0 0 0]
 [0 3 4 3 3 0]
 [0 6 6 4 8 0]
 [0 8 2 5 2 0]
 [0 0 0 0 0 0]]


#Завдання 5
У попередьньому масиві змініть тип даних. Виведіть тип даних до та після зміни

In [106]:
# array = array.astype(np.float32)
print(array.dtype)
array = np.array(array, float)
print(array)
print(array.dtype)

int64
[[3. 4. 3. 3.]
 [6. 6. 4. 8.]
 [8. 2. 5. 2.]]
float64


#Завдання 6
У даному масиві замініть елементи, які дорівнюють\більші\менші за var на -1

In [107]:
x = np.array([1, 5, 3, 8, 6, 5, 7, 4])
var = 5

x[x == var] = -1
print(x)

[ 1 -1  3  8  6 -1  7  4]


#Завдання 7
Замініть пропущені значення матриці(np.nan) на -1

Дивись np.isnan

In [108]:
X = np.array([[1, 2, np.nan, 4],
              [5, np.nan, np.nan, 4],
              [np.nan, 10, 11, np.nan]])
X[np.isnan(X)] = -1
print(X)


[[ 1.  2. -1.  4.]
 [ 5. -1. -1.  4.]
 [-1. 10. 11. -1.]]


#Завдання 8
Створіть матрицю розміру 4х6 з випадковими числами. Змініть її розмір на 3х8

In [109]:
# array = np.random.rand(4, 6)
array = np.random.randint(1, 10, size=(4, 6))
print(array)
print(array.reshape((3, 8)))

[[8 2 2 2 7 2]
 [3 2 7 2 4 9]
 [6 3 1 8 6 1]
 [2 8 9 1 1 2]]
[[8 2 2 2 7 2 3 2]
 [7 2 4 9 6 3 1 8]
 [6 1 2 8 9 1 1 2]]


#Завдання 9
Створіть матрицю з одиниць розміром 3х4. Знайдіть середнє арифметичне(mean) кожного стовпчика

In [110]:
array = np.ones((3, 4), int)
# array[:, :1] = 2
print(array)
array.mean(axis=0)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


array([1., 1., 1., 1.])

#Завдання 10
Створіть випадкову матрицю розміром 5х6. Округліть значення до одного знаку після коми(np.round). Розмістіть стовпчики так, щоб значення в першому рядку були відсортовані за зростанням

In [120]:
array = np.random.rand(5, 6)
print(array)
array = array.round(1)
print(array)
array[0] = np.sort(array[0])
print(array)

[[0.82426701 0.66237634 0.25188588 0.35299942 0.66576451 0.69015104]
 [0.36459637 0.60778095 0.84342725 0.97189299 0.17330146 0.56133614]
 [0.84715459 0.98152268 0.92274563 0.6399297  0.17725102 0.83056249]
 [0.03449462 0.4862023  0.89520944 0.84528898 0.5400736  0.63692563]
 [0.28316489 0.13227146 0.60679119 0.54743554 0.61702348 0.12546661]]
[[0.8 0.7 0.3 0.4 0.7 0.7]
 [0.4 0.6 0.8 1.  0.2 0.6]
 [0.8 1.  0.9 0.6 0.2 0.8]
 [0.  0.5 0.9 0.8 0.5 0.6]
 [0.3 0.1 0.6 0.5 0.6 0.1]]
[[0.3 0.4 0.7 0.7 0.7 0.8]
 [0.4 0.6 0.8 1.  0.2 0.6]
 [0.8 1.  0.9 0.6 0.2 0.8]
 [0.  0.5 0.9 0.8 0.5 0.6]
 [0.3 0.1 0.6 0.5 0.6 0.1]]


#Завдання 11
В даній матриці знайдіть всі елементи зі значенням між 3 і 6

Дивись документацію np.logical_and

In [130]:
X = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10],
              [9, 8, 7, 6, 5],
              [4, 3, 2, 1, 0]])
# Y = np.logical_and(X > 3, X <6)
# print(Y)
# print(X[Y])
Y = X[np.logical_and(X > 3, X <6)]
print(Y)

[[False False False  True  True]
 [False False False False False]
 [False False False False  True]
 [ True False False False False]]
[4 5 5 4]
[4 5 5 4]


#Завдання 12
Створіть випадкову матрицю розміру 5х6. Нормалізуйте стовпчики: від кожного елемента ставпчика відніміть мінімальне значення та поділіть результат на різницю між максимальним та мінімальним елементом цього стовпчика.

Після цього всі значення мають бути в межах [0, 1]

In [138]:
array = np.random.randint(1, 10, size=(5, 6))
print(array)
# minimal = np.min(array, axis=0)
# print(minimal)
minimal = array.min(axis=0)
print(minimal)
array = array - minimal
print(array)
# max_min_dif = array.max(axis=0) - array.min(axis=0)
# print(max_min_dif)
array = array / array.max(axis=0)
print(array)

[[1 9 7 4 4 5]
 [2 4 6 6 4 1]
 [4 2 4 8 2 4]
 [5 4 1 1 6 7]
 [5 4 2 8 3 3]]
[1 2 1 1 2 1]
[[0 7 6 3 2 4]
 [1 2 5 5 2 0]
 [3 0 3 7 0 3]
 [4 2 0 0 4 6]
 [4 2 1 7 1 2]]
[[0.         1.         1.         0.42857143 0.5        0.66666667]
 [0.25       0.28571429 0.83333333 0.71428571 0.5        0.        ]
 [0.75       0.         0.5        1.         0.         0.5       ]
 [1.         0.28571429 0.         0.         1.         1.        ]
 [1.         0.28571429 0.16666667 1.         0.25       0.33333333]]
