<a href="https://colab.research.google.com/github/levchenkopavlo/AI/blob/master/%D0%94%D0%97_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Імпортуйте модуль numpy

In [158]:
import numpy as np

#Завдання 1

Створіть масив з парними числами між 30 і 70

In [159]:
array = np.arange(30,71,2)
print(array)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


#Завдання 2
Створіть масив з 10 числами між 0(включно) та 1(не включно) див документацію

In [160]:
array = np.linspace(0., 1., num=10, endpoint=False)
print(array)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


#Завдання 4
Напишіть функцію яка приймає матрицю розміру nxn та повертає матрицю розміру (n+2) x (n+2), на краях якої розміщенні 0.

In [161]:
def array_transform(array):
  size = array.shape
  blank = np.zeros((size[0]+2, size[1]+2), int)
  print(blank)
  blank[1:-1, 1:-1] = array
  return blank

n, m = 3, 4
array = np.random.randint(1, 9, size=(n, m))
print(array)
print(array_transform(array))
# print(array.dtype)

[[2 5 7 3]
 [8 7 4 2]
 [3 7 7 6]]
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
[[0 0 0 0 0 0]
 [0 2 5 7 3 0]
 [0 8 7 4 2 0]
 [0 3 7 7 6 0]
 [0 0 0 0 0 0]]


#Завдання 5
У попередьньому масиві змініть тип даних. Виведіть тип даних до та після зміни

In [162]:
# array = array.astype(np.float32)
print(array.dtype)
array = np.array(array, float)
print(array)
print(array.dtype)

int64
[[2. 5. 7. 3.]
 [8. 7. 4. 2.]
 [3. 7. 7. 6.]]
float64


#Завдання 6
У даному масиві замініть елементи, які дорівнюють\більші\менші за var на -1

In [163]:
x = np.array([1, 5, 3, 8, 6, 5, 7, 4])
var = 5

x[x == var] = -1
print(x)

[ 1 -1  3  8  6 -1  7  4]


#Завдання 7
Замініть пропущені значення матриці(np.nan) на -1

Дивись np.isnan

In [164]:
X = np.array([[1, 2, np.nan, 4],
              [5, np.nan, np.nan, 4],
              [np.nan, 10, 11, np.nan]])
X[np.isnan(X)] = -1
print(X)


[[ 1.  2. -1.  4.]
 [ 5. -1. -1.  4.]
 [-1. 10. 11. -1.]]


#Завдання 8
Створіть матрицю розміру 4х6 з випадковими числами. Змініть її розмір на 3х8

In [165]:
# array = np.random.rand(4, 6)
array = np.random.randint(1, 10, size=(4, 6))
print(array)
print(array.reshape((3, 8)))

[[3 8 1 7 2 5]
 [5 4 4 2 9 1]
 [5 9 7 2 7 9]
 [8 3 2 8 4 7]]
[[3 8 1 7 2 5 5 4]
 [4 2 9 1 5 9 7 2]
 [7 9 8 3 2 8 4 7]]


#Завдання 9
Створіть матрицю з одиниць розміром 3х4. Знайдіть середнє арифметичне(mean) кожного стовпчика

In [166]:
array = np.ones((3, 4), int)
# array[:, :1] = 2
print(array)
array.mean(axis=0)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


array([1., 1., 1., 1.])

#Завдання 10
Створіть випадкову матрицю розміром 5х6. Округліть значення до одного знаку після коми(np.round). Розмістіть стовпчики так, щоб значення в першому рядку були відсортовані за зростанням

In [167]:
array = np.random.rand(5, 6)
print(array)
array = array.round(1)
print(array)
array[0] = np.sort(array[0])
print(array)

[[0.59289568 0.90242755 0.44859875 0.21680496 0.16052448 0.81661873]
 [0.99835562 0.58472319 0.51612128 0.0718007  0.05859374 0.41572275]
 [0.48467613 0.04436956 0.07338421 0.92251885 0.29878434 0.89058408]
 [0.05296221 0.10205612 0.48981924 0.38583989 0.65614853 0.78651635]
 [0.83019988 0.59419125 0.26661457 0.67569974 0.98800395 0.69324858]]
[[0.6 0.9 0.4 0.2 0.2 0.8]
 [1.  0.6 0.5 0.1 0.1 0.4]
 [0.5 0.  0.1 0.9 0.3 0.9]
 [0.1 0.1 0.5 0.4 0.7 0.8]
 [0.8 0.6 0.3 0.7 1.  0.7]]
[[0.2 0.2 0.4 0.6 0.8 0.9]
 [1.  0.6 0.5 0.1 0.1 0.4]
 [0.5 0.  0.1 0.9 0.3 0.9]
 [0.1 0.1 0.5 0.4 0.7 0.8]
 [0.8 0.6 0.3 0.7 1.  0.7]]


#Завдання 11
В даній матриці знайдіть всі елементи зі значенням між 3 і 6

Дивись документацію np.logical_and

In [168]:
X = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10],
              [9, 8, 7, 6, 5],
              [4, 3, 2, 1, 0]])
# Y = np.logical_and(X > 3, X <6)
# print(Y)
# print(X[Y])
Y = X[np.logical_and(X > 3, X <6)]
print(Y)

[4 5 5 4]


#Завдання 12
Створіть випадкову матрицю розміру 5х6. Нормалізуйте стовпчики: від кожного елемента ставпчика відніміть мінімальне значення та поділіть результат на різницю між максимальним та мінімальним елементом цього стовпчика.

Після цього всі значення мають бути в межах [0, 1]

In [169]:
array = np.random.randint(1, 10, size=(5, 6))
print(array)
# minimal = np.min(array, axis=0)
minimal = array.min(axis=0)
norm_array = array - minimal
norm_array = norm_array / norm_array.max(axis=0)
print(norm_array)

# або
norm_array = (array - array.min(axis=0)) / (array.max(axis=0) - array.min(axis=0))
print(norm_array)

[[5 8 4 8 3 5]
 [7 3 6 4 5 2]
 [2 8 6 1 2 6]
 [4 4 1 3 5 9]
 [3 3 9 7 3 8]]
[[0.6        1.         0.375      1.         0.33333333 0.42857143]
 [1.         0.         0.625      0.42857143 1.         0.        ]
 [0.         1.         0.625      0.         0.         0.57142857]
 [0.4        0.2        0.         0.28571429 1.         1.        ]
 [0.2        0.         1.         0.85714286 0.33333333 0.85714286]]
[[0.6        1.         0.375      1.         0.33333333 0.42857143]
 [1.         0.         0.625      0.42857143 1.         0.        ]
 [0.         1.         0.625      0.         0.         0.57142857]
 [0.4        0.2        0.         0.28571429 1.         1.        ]
 [0.2        0.         1.         0.85714286 0.33333333 0.85714286]]
